#ifndef CSVSPLITTER_GLOBAL_H
#define CSVSPLITTER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CSVSPLITTER_LIBRARY)
#  define CSVSPLITTERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CSVSPLITTERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CSVSPLITTER_GLOBAL_H
