#include "unstatistical.h"
#include <map>

namespace UNStatisticalCodes {

namespace {

QMap<QString, UNStatisticalCode> CODES(std::map<QString, UNStatisticalCode>{
  { QStringLiteral("Afghanistan"),
    UNStatisticalCode(4, QStringLiteral("AFG")) },
  { QStringLiteral("Åland Islands"),
    UNStatisticalCode(248, QStringLiteral("ALA")) },
  { QStringLiteral("Albania"), UNStatisticalCode(8, QStringLiteral("ALB")) },
  { QStringLiteral("Algeria"), UNStatisticalCode(12, QStringLiteral("DZA")) },
  { QStringLiteral("American Samoa"),
    UNStatisticalCode(16, QStringLiteral("ASM")) },
  { QStringLiteral("Andorra"), UNStatisticalCode(20, QStringLiteral("AND")) },
  { QStringLiteral("Angola"), UNStatisticalCode(24, QStringLiteral("AGO")) },
  { QStringLiteral("Anguilla"), UNStatisticalCode(66, QStringLiteral("AIA")) },
  { QStringLiteral("Antarctica"),
    UNStatisticalCode(10, QStringLiteral("ATA")) },
  { QStringLiteral("Antigua and Barbuda"),
    UNStatisticalCode(28, QStringLiteral("ATG")) },
  { QStringLiteral("Argentina"), UNStatisticalCode(32, QStringLiteral("ARG")) },
  { QStringLiteral("Armenia"), UNStatisticalCode(51, QStringLiteral("ARM")) },
  { QStringLiteral("Aruba"), UNStatisticalCode(533, QStringLiteral("ABW")) },
  { QStringLiteral("Australia"), UNStatisticalCode(36, QStringLiteral("AUS")) },
  { QStringLiteral("Austria"), UNStatisticalCode(40, QStringLiteral("AUT")) },
  { QStringLiteral("Azerbaijan"),
    UNStatisticalCode(31, QStringLiteral("AZE")) },
  { QStringLiteral("Bahamas"), UNStatisticalCode(44, QStringLiteral("BHS")) },
  { QStringLiteral("Bahrain"), UNStatisticalCode(48, QStringLiteral("BHR")) },
  { QStringLiteral("Bangladesh"),
    UNStatisticalCode(50, QStringLiteral("BGD")) },
  { QStringLiteral("Barbados"), UNStatisticalCode(52, QStringLiteral("BRB")) },
  { QStringLiteral("Belarus"), UNStatisticalCode(112, QStringLiteral("BLR")) },
  { QStringLiteral("Belgium"), UNStatisticalCode(56, QStringLiteral("BEL")) },
  { QStringLiteral("Belize"), UNStatisticalCode(84, QStringLiteral("BLZ")) },
  { QStringLiteral("Benin"), UNStatisticalCode(204, QStringLiteral("BEN")) },
  { QStringLiteral("Bermuda"), UNStatisticalCode(60, QStringLiteral("BMU")) },
  { QStringLiteral("Bhutan"), UNStatisticalCode(64, QStringLiteral("BTN")) },
  { QStringLiteral("Bolivia"), UNStatisticalCode(68, QStringLiteral("BOL")) },
  { QStringLiteral("Bonaire"), UNStatisticalCode(535, QStringLiteral("BES")) },
  { QStringLiteral("Saba"), UNStatisticalCode(535, QStringLiteral("BES")) },
  { QStringLiteral("Sint Eustatius"),
    UNStatisticalCode(535, QStringLiteral("BES")) },
  { QStringLiteral("Bosnia and Herzegovina"),
    UNStatisticalCode(70, QStringLiteral("BIH")) },
  { QStringLiteral("Bosnia"), UNStatisticalCode(70, QStringLiteral("BIH")) },
  { QStringLiteral("Herzegovina"),
    UNStatisticalCode(70, QStringLiteral("BIH")) },
  { QStringLiteral("Botswana"), UNStatisticalCode(72, QStringLiteral("BWA")) },
  { QStringLiteral("Bouvet Island"),
    UNStatisticalCode(74, QStringLiteral("BVT")) },
  { QStringLiteral("Brazil"), UNStatisticalCode(76, QStringLiteral("BRA")) },
  { QStringLiteral("British Indian Ocean Territory"),
    UNStatisticalCode(86, QStringLiteral("IOT")) },
  { QStringLiteral("British Virgin Islands"),
    UNStatisticalCode(92, QStringLiteral("VGB")) },
  { QStringLiteral("Brunei"), UNStatisticalCode(96, QStringLiteral("BRN")) },
  { QStringLiteral("Brunei Darussalam"),
    UNStatisticalCode(96, QStringLiteral("BRN")) },
  { QStringLiteral("Bulgaria"), UNStatisticalCode(100, QStringLiteral("BGR")) },
  { QStringLiteral("Burkina Faso"),
    UNStatisticalCode(854, QStringLiteral("BFA")) },
  { QStringLiteral("Burundi"), UNStatisticalCode(108, QStringLiteral("BDI")) },
  { QStringLiteral("Cabo Verde"),
    UNStatisticalCode(132, QStringLiteral("CPV")) },
  { QStringLiteral("Cambodia"), UNStatisticalCode(116, QStringLiteral("KHM")) },
  { QStringLiteral("Cameroon"), UNStatisticalCode(120, QStringLiteral("CMR")) },
  { QStringLiteral("Canada"), UNStatisticalCode(124, QStringLiteral("CAN")) },
  { QStringLiteral("Cayman Islands"),
    UNStatisticalCode(136, QStringLiteral("CYM")) },
  { QStringLiteral("Central African Republic"),
    UNStatisticalCode(140, QStringLiteral("CAF")) },
  { QStringLiteral("Chad"), UNStatisticalCode(148, QStringLiteral("TCD")) },
  { QStringLiteral("Chile"), UNStatisticalCode(152, QStringLiteral("CHL")) },
  { QStringLiteral("China"), UNStatisticalCode(156, QStringLiteral("CHN")) },
  { QStringLiteral("China, Hong Kong Special Administrative Region"),
    UNStatisticalCode(344, QStringLiteral("HKG")) },
  { QStringLiteral("China, Macao Special Administrative Region"),
    UNStatisticalCode(446, QStringLiteral("MAC")) },
  { QStringLiteral("Christmas Island"),
    UNStatisticalCode(162, QStringLiteral("CXR")) },
  { QStringLiteral("Cocos (Keeling) Islands"),
    UNStatisticalCode(166, QStringLiteral("CCK")) },
  { QStringLiteral("Colombia"), UNStatisticalCode(170, QStringLiteral("COL")) },
  { QStringLiteral("Comoros"), UNStatisticalCode(174, QStringLiteral("COM")) },
  { QStringLiteral("Congo"), UNStatisticalCode(178, QStringLiteral("COG")) },
  { QStringLiteral("Cook Islands"),
    UNStatisticalCode(184, QStringLiteral("COK")) },
  { QStringLiteral("Costa Rica"),
    UNStatisticalCode(188, QStringLiteral("CRI")) },
  { QStringLiteral("Côte d’Ivoire"),
    UNStatisticalCode(384, QStringLiteral("CIV")) },
  { QStringLiteral("Croatia"), UNStatisticalCode(191, QStringLiteral("HRV")) },
  { QStringLiteral("Cuba"), UNStatisticalCode(192, QStringLiteral("CUB")) },
  { QStringLiteral("Curaçao"), UNStatisticalCode(531, QStringLiteral("CUW")) },
  { QStringLiteral("Cyprus"), UNStatisticalCode(196, QStringLiteral("CYP")) },
  { QStringLiteral("Czechia"), UNStatisticalCode(203, QStringLiteral("CZE")) },
  { QStringLiteral("Democratic People's Republic of Korea"),
    UNStatisticalCode(408, QStringLiteral("PRK")) },
  { QStringLiteral("Democratic Republic of the Congo"),
    UNStatisticalCode(180, QStringLiteral("COD")) },
  { QStringLiteral("Denmark"), UNStatisticalCode(208, QStringLiteral("DNK")) },
  { QStringLiteral("Djibouti"), UNStatisticalCode(262, QStringLiteral("DJI")) },
  { QStringLiteral("Dominica"), UNStatisticalCode(212, QStringLiteral("DMA")) },
  { QStringLiteral("Dominican Republic"),
    UNStatisticalCode(214, QStringLiteral("DOM")) },
  { QStringLiteral("Ecuador"), UNStatisticalCode(218, QStringLiteral("ECU")) },
  { QStringLiteral("Egypt"), UNStatisticalCode(818, QStringLiteral("EGY")) },
  { QStringLiteral("El Salvador"),
    UNStatisticalCode(222, QStringLiteral("SLV")) },
  { QStringLiteral("Equatorial Guinea"),
    UNStatisticalCode(226, QStringLiteral("GNQ")) },
  { QStringLiteral("Eritrea"), UNStatisticalCode(232, QStringLiteral("ERI")) },
  { QStringLiteral("Estonia"), UNStatisticalCode(233, QStringLiteral("EST")) },
  { QStringLiteral("Eswatini"), UNStatisticalCode(748, QStringLiteral("SWZ")) },
  { QStringLiteral("Ethiopia"), UNStatisticalCode(231, QStringLiteral("ETH")) },
  { QStringLiteral("Falkland Islands (Malvinas)"),
    UNStatisticalCode(238, QStringLiteral("FLK")) },
  { QStringLiteral("Faroe Islands"),
    UNStatisticalCode(234, QStringLiteral("FRO")) },
  { QStringLiteral("Fiji"), UNStatisticalCode(242, QStringLiteral("FJI")) },
  { QStringLiteral("Finland"), UNStatisticalCode(246, QStringLiteral("FIN")) },
  { QStringLiteral("France"), UNStatisticalCode(250, QStringLiteral("FRA")) },
  { QStringLiteral("French Guiana"),
    UNStatisticalCode(254, QStringLiteral("GUF")) },
  { QStringLiteral("French Polynesia"),
    UNStatisticalCode(258, QStringLiteral("PYF")) },
  { QStringLiteral("French Southern Territories"),
    UNStatisticalCode(260, QStringLiteral("ATF")) },
  { QStringLiteral("Gabon"), UNStatisticalCode(266, QStringLiteral("GAB")) },
  { QStringLiteral("Gambia"), UNStatisticalCode(270, QStringLiteral("GMB")) },
  { QStringLiteral("Georgia"), UNStatisticalCode(268, QStringLiteral("GEO")) },
  { QStringLiteral("Germany"), UNStatisticalCode(276, QStringLiteral("DEU")) },
  { QStringLiteral("Ghana"), UNStatisticalCode(288, QStringLiteral("GHA")) },
  { QStringLiteral("Gibraltar"),
    UNStatisticalCode(292, QStringLiteral("GIB")) },
  { QStringLiteral("Greece"), UNStatisticalCode(300, QStringLiteral("GRC")) },
  { QStringLiteral("Greenland"),
    UNStatisticalCode(304, QStringLiteral("GRL")) },
  { QStringLiteral("Grenada"), UNStatisticalCode(308, QStringLiteral("GRD")) },
  { QStringLiteral("Guadeloupe"),
    UNStatisticalCode(312, QStringLiteral("GLP")) },
  { QStringLiteral("Guam"), UNStatisticalCode(316, QStringLiteral("GUM")) },
  { QStringLiteral("Guatemala"),
    UNStatisticalCode(320, QStringLiteral("GTM")) },
  { QStringLiteral("Guernsey"), UNStatisticalCode(831, QStringLiteral("GGY")) },
  { QStringLiteral("Guinea"), UNStatisticalCode(324, QStringLiteral("GIN")) },
  { QStringLiteral("Guinea-Bissau"),
    UNStatisticalCode(624, QStringLiteral("GNB")) },
  { QStringLiteral("Guyana"), UNStatisticalCode(328, QStringLiteral("GUY")) },
  { QStringLiteral("Haiti"), UNStatisticalCode(332, QStringLiteral("HTI")) },
  { QStringLiteral("Heard Island and McDonald Islands"),
    UNStatisticalCode(334, QStringLiteral("HMD")) },
  { QStringLiteral("Holy See"), UNStatisticalCode(336, QStringLiteral("VAT")) },
  { QStringLiteral("Honduras"), UNStatisticalCode(340, QStringLiteral("HND")) },
  { QStringLiteral("Hungary"), UNStatisticalCode(348, QStringLiteral("HUN")) },
  { QStringLiteral("Iceland"), UNStatisticalCode(352, QStringLiteral("ISL")) },
  { QStringLiteral("India"), UNStatisticalCode(356, QStringLiteral("IND")) },
  { QStringLiteral("Indonesia"),
    UNStatisticalCode(360, QStringLiteral("IDN")) },
  { QStringLiteral("Iran (Islamic Republic of)"),
    UNStatisticalCode(364, QStringLiteral("IRN")) },
  { QStringLiteral("Iraq"), UNStatisticalCode(368, QStringLiteral("IRQ")) },
  { QStringLiteral("Ireland"), UNStatisticalCode(372, QStringLiteral("IRL")) },
  { QStringLiteral("Isle of Man"),
    UNStatisticalCode(833, QStringLiteral("IMN")) },
  { QStringLiteral("Israel"), UNStatisticalCode(376, QStringLiteral("ISR")) },
  { QStringLiteral("Italy"), UNStatisticalCode(380, QStringLiteral("ITA")) },
  { QStringLiteral("Jamaica"), UNStatisticalCode(388, QStringLiteral("JAM")) },
  { QStringLiteral("Japan"), UNStatisticalCode(392, QStringLiteral("JPN")) },
  { QStringLiteral("Jersey"), UNStatisticalCode(832, QStringLiteral("JEY")) },
  { QStringLiteral("Jordan"), UNStatisticalCode(400, QStringLiteral("JOR")) },
  { QStringLiteral("Kazakhstan"),
    UNStatisticalCode(398, QStringLiteral("KAZ")) },
  { QStringLiteral("Kenya"), UNStatisticalCode(404, QStringLiteral("KEN")) },
  { QStringLiteral("Kiribati"), UNStatisticalCode(296, QStringLiteral("KIR")) },
  { QStringLiteral("Kuwait"), UNStatisticalCode(414, QStringLiteral("KWT")) },
  { QStringLiteral("Kyrgyzstan"),
    UNStatisticalCode(417, QStringLiteral("KGZ")) },
  { QStringLiteral("Lao People's Democratic Republic"),
    UNStatisticalCode(418, QStringLiteral("LAO")) },
  { QStringLiteral("Latvia"), UNStatisticalCode(428, QStringLiteral("LVA")) },
  { QStringLiteral("Lebanon"), UNStatisticalCode(422, QStringLiteral("LBN")) },
  { QStringLiteral("Lesotho"), UNStatisticalCode(426, QStringLiteral("LSO")) },
  { QStringLiteral("Liberia"), UNStatisticalCode(430, QStringLiteral("LBR")) },
  { QStringLiteral("Libya"), UNStatisticalCode(434, QStringLiteral("LBY")) },
  { QStringLiteral("Liechtenstein"),
    UNStatisticalCode(438, QStringLiteral("LIE")) },
  { QStringLiteral("Lithuania"),
    UNStatisticalCode(440, QStringLiteral("LTU")) },
  { QStringLiteral("Luxembourg"),
    UNStatisticalCode(442, QStringLiteral("LUX")) },
  { QStringLiteral("Madagascar"),
    UNStatisticalCode(450, QStringLiteral("MDG")) },
  { QStringLiteral("Malawi"), UNStatisticalCode(454, QStringLiteral("MWI")) },
  { QStringLiteral("Malaysia"), UNStatisticalCode(458, QStringLiteral("MYS")) },
  { QStringLiteral("Maldives"), UNStatisticalCode(462, QStringLiteral("MDV")) },
  { QStringLiteral("Mali"), UNStatisticalCode(466, QStringLiteral("MLI")) },
  { QStringLiteral("Malta"), UNStatisticalCode(470, QStringLiteral("MLT")) },
  { QStringLiteral("Marshall Islands"),
    UNStatisticalCode(584, QStringLiteral("MHL")) },
  { QStringLiteral("Martinique"),
    UNStatisticalCode(474, QStringLiteral("MTQ")) },
  { QStringLiteral("Mauritania"),
    UNStatisticalCode(478, QStringLiteral("MRT")) },
  { QStringLiteral("Mauritius"),
    UNStatisticalCode(480, QStringLiteral("MUS")) },
  { QStringLiteral("Mayotte"), UNStatisticalCode(175, QStringLiteral("MYT")) },
  { QStringLiteral("Mexico"), UNStatisticalCode(484, QStringLiteral("MEX")) },
  { QStringLiteral("Micronesia (Federated States of)"),
    UNStatisticalCode(583, QStringLiteral("FSM")) },
  { QStringLiteral("Monaco"), UNStatisticalCode(492, QStringLiteral("MCO")) },
  { QStringLiteral("Mongolia"), UNStatisticalCode(496, QStringLiteral("MNG")) },
  { QStringLiteral("Montenegro"),
    UNStatisticalCode(499, QStringLiteral("MNE")) },
  { QStringLiteral("Montserrat"),
    UNStatisticalCode(500, QStringLiteral("MSR")) },
  { QStringLiteral("Morocco"), UNStatisticalCode(504, QStringLiteral("MAR")) },
  { QStringLiteral("Mozambique"),
    UNStatisticalCode(508, QStringLiteral("MOZ")) },
  { QStringLiteral("Myanmar"), UNStatisticalCode(104, QStringLiteral("MMR")) },
  { QStringLiteral("Namibia"), UNStatisticalCode(516, QStringLiteral("NAM")) },
  { QStringLiteral("Nauru"), UNStatisticalCode(520, QStringLiteral("NRU")) },
  { QStringLiteral("Nepal"), UNStatisticalCode(524, QStringLiteral("NPL")) },
  { QStringLiteral("Netherlands"),
    UNStatisticalCode(528, QStringLiteral("NLD")) },
  { QStringLiteral("New Caledonia"),
    UNStatisticalCode(540, QStringLiteral("NCL")) },
  { QStringLiteral("New Zealand"),
    UNStatisticalCode(554, QStringLiteral("NZL")) },
  { QStringLiteral("Nicaragua"),
    UNStatisticalCode(558, QStringLiteral("NIC")) },
  { QStringLiteral("Niger"), UNStatisticalCode(562, QStringLiteral("NER")) },
  { QStringLiteral("Nigeria"), UNStatisticalCode(566, QStringLiteral("NGA")) },
  { QStringLiteral("Niue"), UNStatisticalCode(570, QStringLiteral("NIU")) },
  { QStringLiteral("Norfolk Island"),
    UNStatisticalCode(574, QStringLiteral("NFK")) },
  { QStringLiteral("North Macedonia"),
    UNStatisticalCode(807, QStringLiteral("MKD")) },
  { QStringLiteral("Northern Mariana Islands"),
    UNStatisticalCode(580, QStringLiteral("MNP")) },
  { QStringLiteral("Norway"), UNStatisticalCode(578, QStringLiteral("NOR")) },
  { QStringLiteral("Oman"), UNStatisticalCode(512, QStringLiteral("OMN")) },
  { QStringLiteral("Pakistan"), UNStatisticalCode(586, QStringLiteral("PAK")) },
  { QStringLiteral("Palau"), UNStatisticalCode(585, QStringLiteral("PLW")) },
  { QStringLiteral("Panama"), UNStatisticalCode(591, QStringLiteral("PAN")) },
  { QStringLiteral("Papua New Guinea"),
    UNStatisticalCode(598, QStringLiteral("PNG")) },
  { QStringLiteral("Paraguay"), UNStatisticalCode(600, QStringLiteral("PRY")) },
  { QStringLiteral("Peru"), UNStatisticalCode(604, QStringLiteral("PER")) },
  { QStringLiteral("Philippines"),
    UNStatisticalCode(608, QStringLiteral("PHL")) },
  { QStringLiteral("Pitcairn"), UNStatisticalCode(612, QStringLiteral("PCN")) },
  { QStringLiteral("Poland"), UNStatisticalCode(616, QStringLiteral("POL")) },
  { QStringLiteral("Portugal"), UNStatisticalCode(620, QStringLiteral("PRT")) },
  { QStringLiteral("Puerto Rico"),
    UNStatisticalCode(630, QStringLiteral("PRI")) },
  { QStringLiteral("Qatar"), UNStatisticalCode(634, QStringLiteral("QAT")) },
  { QStringLiteral("Republic of Korea"),
    UNStatisticalCode(410, QStringLiteral("KOR")) },
  { QStringLiteral("Republic of Moldova"),
    UNStatisticalCode(498, QStringLiteral("MDA")) },
  { QStringLiteral("Réunion"), UNStatisticalCode(638, QStringLiteral("REU")) },
  { QStringLiteral("Romania"), UNStatisticalCode(642, QStringLiteral("ROU")) },
  { QStringLiteral("Russian Federation"),
    UNStatisticalCode(643, QStringLiteral("RUS")) },
  { QStringLiteral("Rwanda"), UNStatisticalCode(646, QStringLiteral("RWA")) },
  { QStringLiteral("Saint Barthélemy"),
    UNStatisticalCode(652, QStringLiteral("BLM")) },
  { QStringLiteral("Saint Helena"),
    UNStatisticalCode(654, QStringLiteral("SHN")) },
  { QStringLiteral("Saint Kitts and Nevis"),
    UNStatisticalCode(659, QStringLiteral("KNA")) },
  { QStringLiteral("Saint Lucia"),
    UNStatisticalCode(662, QStringLiteral("LCA")) },
  { QStringLiteral("Saint Martin (French Part)"),
    UNStatisticalCode(663, QStringLiteral("MAF")) },
  { QStringLiteral("Saint Pierre and Miquelon"),
    UNStatisticalCode(666, QStringLiteral("SPM")) },
  { QStringLiteral("Saint Vincent and the Grenadines"),
    UNStatisticalCode(670, QStringLiteral("VCT")) },
  { QStringLiteral("Samoa"), UNStatisticalCode(882, QStringLiteral("WSM")) },
  { QStringLiteral("San Marino"),
    UNStatisticalCode(674, QStringLiteral("SMR")) },
  { QStringLiteral("Sao Tome and Principe"),
    UNStatisticalCode(678, QStringLiteral("STP")) },
  { QStringLiteral("Sark"), UNStatisticalCode(680, QStringLiteral("")) },
  { QStringLiteral("Saudi Arabia"),
    UNStatisticalCode(682, QStringLiteral("SAU")) },
  { QStringLiteral("Senegal"), UNStatisticalCode(686, QStringLiteral("SEN")) },
  { QStringLiteral("Serbia"), UNStatisticalCode(688, QStringLiteral("SRB")) },
  { QStringLiteral("Seychelles"),
    UNStatisticalCode(690, QStringLiteral("SYC")) },
  { QStringLiteral("Sierra Leone"),
    UNStatisticalCode(694, QStringLiteral("SLE")) },
  { QStringLiteral("Singapore"),
    UNStatisticalCode(702, QStringLiteral("SGP")) },
  { QStringLiteral("Sint Maarten (Dutch part)"),
    UNStatisticalCode(534, QStringLiteral("SXM")) },
  { QStringLiteral("Slovakia"), UNStatisticalCode(703, QStringLiteral("SVK")) },
  { QStringLiteral("Slovenia"), UNStatisticalCode(705, QStringLiteral("SVN")) },
  { QStringLiteral("Solomon Islands"),
    UNStatisticalCode(90, QStringLiteral("SLB")) },
  { QStringLiteral("Somalia"), UNStatisticalCode(706, QStringLiteral("SOM")) },
  { QStringLiteral("South Africa"),
    UNStatisticalCode(710, QStringLiteral("ZAF")) },
  { QStringLiteral("South Georgia and the South Sandwich Islands"),
    UNStatisticalCode(239, QStringLiteral("SGS")) },
  { QStringLiteral("South Sudan"),
    UNStatisticalCode(728, QStringLiteral("SSD")) },
  { QStringLiteral("Spain"), UNStatisticalCode(724, QStringLiteral("ESP")) },
  { QStringLiteral("Sri Lanka"),
    UNStatisticalCode(144, QStringLiteral("LKA")) },
  { QStringLiteral("State of Palestine"),
    UNStatisticalCode(275, QStringLiteral("PSE")) },
  { QStringLiteral("Sudan"), UNStatisticalCode(729, QStringLiteral("SDN")) },
  { QStringLiteral("Suriname"), UNStatisticalCode(740, QStringLiteral("SUR")) },
  { QStringLiteral("Svalbard and Jan Mayen Islands"),
    UNStatisticalCode(744, QStringLiteral("SJM")) },
  { QStringLiteral("Sweden"), UNStatisticalCode(752, QStringLiteral("SWE")) },
  { QStringLiteral("Switzerland"),
    UNStatisticalCode(756, QStringLiteral("CHE")) },
  { QStringLiteral("Syrian Arab Republic"),
    UNStatisticalCode(760, QStringLiteral("SYR")) },
  { QStringLiteral("Tajikistan"),
    UNStatisticalCode(762, QStringLiteral("TJK")) },
  { QStringLiteral("Thailand"), UNStatisticalCode(764, QStringLiteral("THA")) },
  { QStringLiteral("Timor-Leste"),
    UNStatisticalCode(626, QStringLiteral("TLS")) },
  { QStringLiteral("Togo"), UNStatisticalCode(768, QStringLiteral("TGO")) },
  { QStringLiteral("Tokelau"), UNStatisticalCode(772, QStringLiteral("TKL")) },
  { QStringLiteral("Tonga"), UNStatisticalCode(776, QStringLiteral("TON")) },
  { QStringLiteral("Trinidad and Tobago"),
    UNStatisticalCode(780, QStringLiteral("TTO")) },
  { QStringLiteral("Tunisia"), UNStatisticalCode(788, QStringLiteral("TUN")) },
  { QStringLiteral("Turkey"), UNStatisticalCode(792, QStringLiteral("TUR")) },
  { QStringLiteral("Turkmenistan"),
    UNStatisticalCode(795, QStringLiteral("TKM")) },
  { QStringLiteral("Turks and Caicos Islands"),
    UNStatisticalCode(796, QStringLiteral("TCA")) },
  { QStringLiteral("Tuvalu"), UNStatisticalCode(798, QStringLiteral("TUV")) },
  { QStringLiteral("Uganda"), UNStatisticalCode(800, QStringLiteral("UGA")) },
  { QStringLiteral("Ukraine"), UNStatisticalCode(804, QStringLiteral("UKR")) },
  { QStringLiteral("United Arab Emirates"),
    UNStatisticalCode(784, QStringLiteral("ARE")) },
  { QStringLiteral("United Kingdom of Great Britain and Northern Ireland"),
    UNStatisticalCode(826, QStringLiteral("GBR")) },
  { QStringLiteral("United Republic of Tanzania"),
    UNStatisticalCode(834, QStringLiteral("TZA")) },
  { QStringLiteral("United States Minor Outlying Islands"),
    UNStatisticalCode(581, QStringLiteral("UMI")) },
  { QStringLiteral("United States of America"),
    UNStatisticalCode(840, QStringLiteral("USA")) },
  { QStringLiteral("United States Virgin Islands"),
    UNStatisticalCode(850, QStringLiteral("VIR")) },
  { QStringLiteral("Uruguay"), UNStatisticalCode(858, QStringLiteral("URY")) },
  { QStringLiteral("Uzbekistan"),
    UNStatisticalCode(860, QStringLiteral("UZB")) },
  { QStringLiteral("Vanuatu"), UNStatisticalCode(548, QStringLiteral("VUT")) },
  { QStringLiteral("Venezuela (Bolivarian Republic of)"),
    UNStatisticalCode(862, QStringLiteral("VEN")) },
  { QStringLiteral("Viet Nam"), UNStatisticalCode(704, QStringLiteral("VNM")) },
  { QStringLiteral("Wallis and Futuna Islands"),
    UNStatisticalCode(876, QStringLiteral("WLF")) },
  { QStringLiteral("Western Sahara"),
    UNStatisticalCode(732, QStringLiteral("ESH")) },
  { QStringLiteral("Yemen"), UNStatisticalCode(887, QStringLiteral("YEM")) },
  { QStringLiteral("Zambia"), UNStatisticalCode(894, QStringLiteral("ZMB")) },
  { QStringLiteral("Zimbabwe"),
    UNStatisticalCode(716, QStringLiteral("ZWE")) } });

UNStatisticalCode
code(const QString& name)
{
  return CODES.value(name);
}

} // end anonymous namespace

QStringList
names()
{
  return CODES.keys();
}

int
numericalCode(const QString& name)
{
  return CODES.value(name).m49Code;
}

QString
numericalCodeString(const QString& name)
{
  QString numerical("%1");
  return numerical.arg(CODES.value(name).m49Code, 3, 10, QChar('0'));
}

QString
alphaCode(const QString& name)
{
  return CODES.value(name).alpha;
}

} // end namespace UNStatisticalCodes
